# Generated by Django 4.2.13 on 2024-06-04 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="дата выхода на рынок"
            ),
        ),
    ]
